version: '3'
services:
  postgres:
    container_name: postgres-authen
    image: postgres
    ports:
      - '5432:5432'
    # volumes:
    #   - "/data/postgres:/data/postgres"
    env_file:
      - docker.env
    networks:
      - postgres
  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - '80:80'
    # volumes:
    #   - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8081:8081'
    depends_on:
      - redis
#  nestjs-api:
#    build:
#      context: .
#    env_file:
#      - .env
#    ports:
#      - "3000:3000"
#    depends_on:
#      - postgres
#    networks:
#      - postgres
networks:
  postgres:
    driver: bridge
